name: Create Module, Push to Powershell Gallery

on:
  push:
    paths:
    - 'pester/CIS4Azure.Tests.ps1'
    - '.github/workflows/push-to-PowershellGallery.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Module, Push to PSGallery
      run: |
        Publish-Script -Name './pester/CIS4Azure.Tests.ps1' -NuGetApiKey '${{ secrets.cis4azure_powershell_gallery_api_key }}'
      shell: pwsh